# Generated by Django 5.1.7 on 2025-03-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancyhh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(max_length=50, unique=True, verbose_name='ID вакансии hh.ru')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город/Регион')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Вакансия hh.ru',
                'verbose_name_plural': 'Вакансии hh.ru',
            },
        ),
    ]
