# Generated by Django 5.1.7 on 2025-03-22 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор'),
        ),
    ]
