QUERY_LIST = [
    # --- Роли и синонимы (EN / RU) ---
    "Product Owner",
    "Digital Product Owner",
    "PO",
    "Продукт Оунер",
    "Продуктовладелец",
    "Product Manager",
    "Project Manager",
    "PM",
    "Проджект Менеджер",
    "Scrum Master",
    "Скрам-мастер",
    "Business Analyst",
    "Бизнес-аналитик",
    "BA",
    "System Analyst",
    "Системный аналитик",
    "UX Researcher",
    "Исследователь UX",
    "User Experience Researcher",
    "UX/UI Designer",
    "UI/UX Designer",
    "Дизайнер UI/UX",
    "UX Designer",
    "UX Writer",
    "Технический писатель (UX)",
    "Enterprise Architect",
    "EA",
    "Архитектор корпоративных систем",
    "Security Architect",
    "Sec Arch",
    "Архитектор безопасности",
    "Data Architect",
    "DA",
    "Архитектор данных",
    "SecOps Engineer",
    "SecOps",
    "SecOps инженер",
    "AppSec Engineer",
    "AppSec",
    "AppSec инженер",
    "DevOps Engineer",
    "DevOps",
    "Системный инженер DevOps",
    "System Administrator",
    "Sysadmin",
    "Системный администратор",
    "Relational Database Administrator",
    "RDBA",
    "Oracle DBA",
    "SQL Server DBA",
    "PostgreSQL DBA",
    "MySQL DBA",
    "NoSQL Database Administrator",
    "NoSQL DBA",
    "MongoDB DBA",
    "Cassandra DBA",
    "Network Engineer (Cisco)",
    "Сетевой инженер (Cisco)",
    "Cyber Security Engineer",
    "Инженер кибербезопасности",
    "Web Developer",
    "Веб-разработчик",
    "Front-end Developer",
    "Backend Developer",
    "Android Developer",
    "Android-разработчик",
    "iOS Developer",
    "iOS-разработчик",
    "Kotlin Multiplatform Engineer",
    "Java Developer",
    "Java-разработчик",
    "C# Developer",
    "C# / .NET Developer",
    ".NET Developer",
    "Python Developer",
    "Python-разработчик",
    "Erlang Developer",
    "Elixir Developer",
    "Erlang / Elixir Developer",
    "Full-Stack Developer",
    "Фулстек-разработчик",
    "RPA Developer",
    "UiPath Developer",
    "HCL/Lotus Notes Developer",
    "Lotus Notes Developer",
    "1C Developer",
    "1С-программист",
    "1С-разработчик",
    "EQ / RPG Analyst",
    "RPG Analyst",
    "EQ / RPG Developer",
    "RPG Developer",
    "AS400 Developer",
    "Web QA",
    "QA Engineer",
    "Тестировщик веб-приложений",
    "Mobile QA",
    "Тестировщик мобильных приложений",
    "Load / Performance QA",
    "Performance Tester",
    "Release Manager",
    "Менеджер по релизам",
    "Data Analyst",
    "Аналитик данных",
    "Web Analyst",
    "Веб-аналитик",
    "MLOps Engineer",
    "DS / ML Engineer",
    "Data Scientist",
    "ML Engineer",
    "AI Engineer",
    "Technical Support Engineer",
    "Tech Support",
    "IT Auditor",
    "IT-аудитор",
    "Monitoring Engineer",
    "Инженер мониторинга",
    "Penetration Tester",
    "Pentester",
    "Security Auditor",
    "Аудитор безопасности",
    "Digital Marketer",
    "Интернет-маркетолог",
    "Internet Marketer",
    "SOC Engineer",
    "SIEM Engineer",
    "Data Engineer",
    "BI Analyst",
    "BI-аналитик",
    "Marketing Analyst",
    "Маркетинговый аналитик",

    # --- Технологии, фреймворки, инструменты (здесь в алфавитном порядке, где уместно) ---
    "1С:Предприятие",
    "ABAP",  # (иногда в SAP-контексте, если нужно)
    "A/B testing",
    "Aha!",
    "Airflow",
    "AISec",
    "Amazon EC2",
    "Amazon EMR",
    "Amazon Redshift",
    "Ansible",
    "AnyDesk",
    "Apache Cassandra",
    "Apache Hadoop",
    "Apache Hive",
    "Apache Kafka",
    "Apache Spark",
    "AppDynamics",
    "Appium",
    "Archimate",
    "Terraform",
    "ArchiMate",
    "ArcSight",
    "Asana",
    "ASP.NET MVC",
    "Azure",
    "Azure DevOps",
    "Balsamiq",
    "Bash",
    "Bitbucket",
    "Blue Prism",
    "Blazor",
    "BPMN",
    "Burp Suite",
    "C#",
    "C++",
    "C",
    "Cassandra",
    "Chef",
    "ClickUp",
    "CocoaPods",
    "Cognos",  # (IBM BI)
    "Confluence",
    "CouchDB",
    "CrowdStrike",
    "CSS3",
    "Data Studio",
    "Django",
    "Docker",
    "Draw.io",
    "Elixir",
    "Elasticsearch",
    "Erlang",
    "Excel",
    "F#",
    "FastAPI",
    "Firebase",
    "Figma",
    "Flask",
    "Flood.io",
    "Foglight",  # иногда для DB мониторинга
    "Full-Stack",
    "Gantt Charts",
    "Gatling",
    "Git",
    "GitHub",
    "GitHub Actions",
    "GitLab",
    "GitLab CI",
    "Go",
    "Google Ads",
    "Google Analytics",
    "Google BigQuery",
    "Google Cloud Platform",
    "Google Optimize",
    "Grafana",
    "Groovy",
    "HCL Domino",
    "HCL Lotus Notes",
    "Helm",
    "Hibernate",
    "Hotjar",
    "HTML5",
    "HttpClient",
    "Hyper-V",
    "IBM i",
    "IBM QRadar",
    "IBM Rational",
    "Illustrator",
    "Informatica",
    "InVision",
    "iOS SDK",
    "ITIL",
    "Jama",
    "Java",
    "JavaScript",
    "Jenkins",
    "Jira",
    "JMeter",
    "Jupyter Notebook",
    "K8s",  # Kubernetes
    "Kanban",
    "Kibana",
    "Kotlin",
    "Kotlin Multiplatform",
    "Kubeflow",
    "Kubernetes",
    "Lucidchart",
    "LXC/LXD",
    "Maven",
    "Metasploit",
    "Microsoft Project",
    "Microsoft Teams",
    "Miro",
    "MongoDB",
    "MSSQL",
    "MySQL",
    "Nagios",
    "Nessus",
    "NetApp",  # иногда в Storage-контексте
    "Network Engineer",
    "Nginx",
    "Nmap",
    "Node.js",
    "Notion",
    "Numpy",
    "OAuth",
    "OpenCV",
    "OpenShift",
    "OpenStack",
    "OpenVAS",
    "Oracle",
    "Palo Alto",
    "Penetration Testing",
    "Pentaho",
    "Photoshop",
    "PHP",
    "Power BI",
    "PowerShell",
    "PRINCE2",
    "ProductPlan",
    "Prometheus",
    "Python",
    "PyTorch",
    "QlikView",
    "Quantitative Analysis",
    "RabbitMQ",
    "Racket",
    "Raspberry Pi",  # иногда в DevOps/IoT контексте
    "React",
    "Redis",
    "Redmine",
    "Redux",
    "Revit",  # в BIM контекстах, нечасто в IT
    "Risk Assessment",
    "RPA",
    "Ruby on Rails",
    "Rust",  # иногда
    "Salesforce",
    "SAP",
    "Scala",
    "Scrum",
    "Selenium",
    "SEO",
    "ServiceNow",
    "SharePoint",
    "SIEM",
    "SLA",
    "SLSA",
    "Snowflake",
    "SOAP",
    "SOC",
    "SOAR",
    "SonarQube",
    "Spark",
    "Splunk",
    "SQL",
    "SQL Server",
    "Storybook",  # часто для Front-End UI
    "Swagger",
    "Swift",
    "SwiftUI",
    "Symfony",
    "Tableau",
    "Tailwind CSS",  # в современных фронтенд-стэках
    "Talend",
    "Tampermonkey",  # редко для скриптов в браузере
    "TeamCity",
    "TensorFlow",
    "Terraform",
    "Trello",
    "TypeScript",
    "UML",
    "UiPath",
    "Unity",  # иногда для мобильных
    "Unreal Engine",  # иногда в C++ контексте
    "VBScript",
    "Visio",
    "Visual Studio",
    "Visual Studio Code",
    "VMware",
    "VWO",
    "Vite",
    "Vue.js",
    "Web Analytics",
    "Webpack",
    "Wireshark",
    "WPF",
    "XML",
    "Xcode",
    "Yandex.Metrica",
    "Zeplin",
    "Zabbix",
    "Zap (OWASP)",
    "Zephyr",
    "Zoom",
]