# Generated by Django 4.2.20 on 2025-03-16 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Промпт для Gemini AI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Промпт для AI',
                'verbose_name_plural': 'Промпт для AI',
            },
        ),
        migrations.CreateModel(
            name='GeminiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат обработки AI с сайта',
                'verbose_name_plural': 'Результаты обработки AI с сайта',
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('geo', models.CharField(max_length=255, verbose_name='Локация')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('grade', models.CharField(max_length=255, verbose_name='Грейд')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Min')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Max')),
                ('bonus', models.CharField(blank=True, max_length=255, verbose_name='Бонус')),
                ('bonus_conditions', models.CharField(blank=True, max_length=255, verbose_name='Описание бонуса')),
                ('currency', models.CharField(max_length=50, verbose_name='Валюта')),
                ('gross_net', models.CharField(max_length=50, verbose_name='Gross/Net')),
                ('work_format', models.CharField(max_length=255, verbose_name='Формат работы')),
                ('date_posted', models.DateField(verbose_name='Дата')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Источник')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание вакансии')),
            ],
            options={
                'verbose_name': 'Сохраненная вакансия',
                'verbose_name_plural': 'Сохраненные вакансии',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGeminiPrompt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Промпт для Gemini AI')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Промпт для AI',
                'verbose_name_plural': 'historical Промпт для AI',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
