# Generated by Django 4.2.20 on 2025-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus_conditions', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('gross_net', models.CharField(max_length=10)),
                ('work_format', models.CharField(max_length=50)),
                ('date_posted', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
