# Generated by Django 4.2.20 on 2025-03-18 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='geo',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='grade',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialization',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Специализация'),
        ),
    ]
