# Generated by Django 4.2.20 on 2025-03-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_geminiresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Промпт для Gemini AI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='geminiresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='geminiresult',
            name='input_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='geminiresult',
            name='processed_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='bonus',
            field=models.CharField(blank=True, default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='bonus_conditions',
            field=models.CharField(blank=True, default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='geo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='grade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='gross_net',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(max_length=255),
        ),
    ]
