# Generated by Django 4.2.20 on 2025-03-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_geminiprompt_alter_geminiresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание вакансии'),
        ),
    ]
