# Generated by Django 5.1.7 on 2025-03-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_options_aidialogue_aidialoguemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidialoguemessage',
            name='dialogue',
        ),
        migrations.DeleteModel(
            name='AIDialogue',
        ),
        migrations.DeleteModel(
            name='AIDialogueMessage',
        ),
    ]
