# Generated by Django 4.2.20 on 2025-03-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
    ]
