# Generated by Django 4.2.20 on 2025-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс к BYN')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['currency'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
