# Generated by Django 4.2.20 on 2025-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(50, 'Low'), (25, 'Medium'), (5, 'High'), (0, 'Critical')], default=50),
        ),
    ]
